import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ModelViewer from "../components/ModelViewer";
import {Menu} from "@/components/Menu";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col md:flex-row h-screen w-screen">
          {/* Контент страниц слева (или сверху на мобилках) */}
          <main className="w-full md:w-1/2 h-1/2 md:h-full z-10 relative flex flex-col justify-center items-center">
            {children}
          </main>
          {/* Модель справа (или снизу на мобилках) */}
          <div className="w-full md:w-1/2 h-1/2 md:h-full relative">
            <ModelViewer />
          </div>
        </div>
      </body>
    </html>
  );
}
